version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1b0zrens5alx2"
s3_prefix = "resume"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
